name: sampleCI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Join in the docker folder
      run: | 
        ls
        touch sample.txt
        pwd
        cd infra/docker
        pwd
        docker compose build
    - name: Build the app
      run: | 
        pwd
        ls
        
